# Generated by Django 2.2.7 on 2019-11-20 20:01

from django.db import migrations
import django_encrypted_filefield.fields
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_encrypted_filefield.fields.EncryptedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
    ]
