# Generated by Django 2.2.7 on 2019-11-29 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='content_liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
