# Generated by Django 2.2.7 on 2019-11-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0002_auto_20191120_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circle', to='stay_close.Content'),
        ),
    ]
