# Generated by Django 2.2.7 on 2019-11-24 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0003_auto_20191122_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='caption',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
    ]
