# Generated by Django 2.2.7 on 2019-11-29 00:15

import datetime
from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0003_auto_20191129_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='created_at',
            field=encrypted_fields.fields.EncryptedDateField(default=datetime.date.today),
        ),
    ]
