# Generated by Django 2.2.7 on 2019-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0004_auto_20191124_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='content',
        ),
        migrations.AddField(
            model_name='circle',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='circle', to='stay_close.Content'),
        ),
    ]
