# Generated by Django 2.2.7 on 2019-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0004_auto_20191129_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img_post',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
