# Generated by Django 2.2.7 on 2019-12-03 20:20

from django.db import migrations
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0005_auto_20191203_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='created_at',
            field=encrypted_fields.fields.EncryptedDateTimeField(default=django.utils.timezone.now),
        ),
    ]
