# Generated by Django 2.2.7 on 2019-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0005_auto_20191124_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='circle', to='stay_close.Content'),
        ),
    ]
