# Generated by Django 2.2.7 on 2019-11-24 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0006_auto_20191124_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='stay_close.Circle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
