# Generated by Django 2.2.7 on 2019-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0007_auto_20191204_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
