# Generated by Django 2.2.7 on 2019-11-25 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0007_auto_20191124_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
