# Generated by Django 2.2.7 on 2019-11-26 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0008_auto_20191125_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='register_link',
        ),
        migrations.AddField(
            model_name='circle',
            name='pending_members',
            field=models.ManyToManyField(blank=True, default=None, related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='circle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='stay_close.Circle'),
            preserve_default=False,
        ),
    ]
