# Generated by Django 2.2.7 on 2019-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0008_auto_20191125_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
