# Generated by Django 2.2.7 on 2019-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0009_auto_20191206_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://stay-close-media.s3.amazonaws.com/images/user.svg?AWSAccessKeyId=AKIA4NZF35JMBULXIMH4&Signature=HrzZ%2FliJ%2FyTlzwIpFfsmxFhANoY%3D&Expires=1575670202', max_length=300, upload_to='images'),
        ),
    ]
