# Generated by Django 2.2.7 on 2019-11-26 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0009_auto_20191126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='pending_members',
            field=models.ManyToManyField(blank=True, related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
