# Generated by Django 2.2.7 on 2019-11-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0009_content_author'),
        ('stay_close', '0010_auto_20191126_2345'),
    ]

    operations = [
    ]
