# Generated by Django 2.2.7 on 2019-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0012_auto_20191206_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/images/user.svg', max_length=300, upload_to='images'),
        ),
    ]
