# Generated by Django 2.2.7 on 2019-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_close', '0012_auto_20191128_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
